# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_types',
            new_name='NewsTypes',
        ),
    ]
