# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170828_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newstypes',
            options={'verbose_name_plural': 'News Types'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='uploaded_at',
            new_name='uploaded_on',
        ),
        migrations.RemoveField(
            model_name='news',
            name='data',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default='News yet to added'),
        ),
        migrations.AlterField(
            model_name='news',
            name='authors',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
