# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:08
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170829_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='Anonymous', editable=False, populate_from='title', unique=True),
        ),
    ]
