# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:16
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20170830_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default='null', editable=False, null=True, populate_from='title'),
        ),
    ]
