# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 05:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170830_0521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='uploaded_on',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='title', editable=False, populate_from='title', unique=True),
        ),
    ]
