# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='token',
            field=models.CharField(default='123456789', max_length=40),
        ),
    ]
